Repository microsoft/PowerShellForGitHub, pull requests merged in 2020-09, with the labels that each got.

#283 Fix default logPath when no user profile is available
  GitHubConfiguration.ps1
  USAGE.md
Labels: bug

#284 Update module to 0.15.1
  CHANGELOG.md
  PowerShellForGitHub.psd1
Labels: release

#288 Fix typos in USAGE.md
  USAGE.md
Labels: bug, documentation
