Repository microsoft/PowerShellForGitHub, pull requests merged in 2020-05, with the labels that each got.

#160 Add core functionality for Project API's
  GitHubProjects.ps1
  PowerShellForGitHub.psd1
  Tests/GitHubProjects.tests.ps1
Labels: api completeness, api-project

#162 Adding functionality for Project Columns
  GitHubProjectColumns.ps1
  PowerShellForGitHub.psd1
  Tests/GitHubProjectColumns.tests.ps1
Labels: api completeness, api-project

#163 Adding functionality for Project Cards
  GitHubProjectCards.ps1
  PowerShellForGitHub.psd1
  Tests/GitHubProjectCards.tests.ps1
Labels: api completeness, api-project

#164 Project Usage
  USAGE.md
Labels: api-project

#179 Fix the behavior of Get-GitHubRepository
  GitHubCore.ps1
  GitHubRepositories.ps1
  Tests/GitHubRepositories.tests.ps1
Labels: bug, technical debt

#181 Fixing the hash of the Tests/Config/Settings.ps1
  GitHubConfiguration.ps1
  build/pipelines/azure-pipelines.ci.yaml
Labels: build

#180 Get PSScriptAnalyzer clean again
  GitHubAnalytics.ps1
  GitHubAssignees.ps1
  GitHubBranches.ps1
  GitHubComments.ps1
  GitHubCore.ps1
  GitHubIssues.ps1
  GitHubLabels.ps1
  GitHubMilestones.ps1
  GitHubMiscellaneous.ps1
  GitHubOrganizations.ps1
  GitHubProjectCards.ps1
  GitHubProjectColumns.ps1
  GitHubProjects.ps1
  GitHubRepositoryForks.ps1
  GitHubRepositoryTraffic.ps1
  GitHubTeams.ps1
  GitHubUsers.ps1
  Helpers.ps1
  NugetTools.ps1
  PowerShellForGitHub.psd1
  Tests/GitHubProjectCards.tests.ps1
  Tests/GitHubProjectColumns.tests.ps1
  Tests/GitHubProjects.tests.ps1
  build/scripts/Write-SignConfigXml.ps1
Labels: technical debt

#173 Update usage documentation for configuring authentication unattended
  GitHubConfiguration.ps1
  README.md
Labels: documentation

#188 Fix named branch querying in Get-GitHubRepositoryBranch
  GitHubBranches.ps1
Labels: bug

#191 Remove references to paid plans from documentation
  GitHubRepositories.ps1
Labels: bug, documentation

#183 Fixing the CI build
  .gitattributes
  CONTRIBUTING.md
  Tests/GitHubContents.tests.ps1
  build/pipelines/azure-pipelines.ci.yaml
  build/pipelines/templates/run-unitTests.yaml
Labels: build

#196 Exception in New-GitHubRepository when specifying TeamId
  GitHubRepositories.ps1
Labels: bug

#199 Fix multi-result behavior across all versions of PowerShell (fixes CI UT's on all platforms)
  GitHubCore.ps1
  Tests/GitHubAnalytics.tests.ps1
  Tests/GitHubAssignees.tests.ps1
  Tests/GitHubLabels.tests.ps1
  Tests/GitHubMilestones.tests.ps1
  Tests/GitHubProjectCards.tests.ps1
  Tests/GitHubProjectColumns.tests.ps1
  Tests/GitHubProjects.tests.ps1
  Tests/GitHubReleases.tests.ps1
  Tests/GitHubRepositories.tests.ps1
  Tests/GitHubRepositoryForks.tests.ps1
  Tests/GitHubRepositoryTraffic.tests.ps1
Labels: bug, build

#201 Add security reporting policy documentation
  README.md
  SECURITY.md
Labels: documentation

#202 Add some additional badges to the README
  README.md
Labels: documentation

#185 Add automatic daily update checking
  GitHubConfiguration.ps1
  GitHubCore.ps1
  PowerShellForGitHub.psd1
  README.md
  UpdateCheck.ps1
Labels: enhancement

#203 Update module to 0.14.0
  CHANGELOG.md
  PowerShellForGitHub.psd1
Labels: release

#204 UpdateCheck must handle when module is newer than published version
  UpdateCheck.ps1
Labels: bug

#207 Speed up Pester tests by using -NoStatus
  Tests/Common.ps1
Labels: build, test
