Repository microsoft/PowerShellForGitHub, pull requests merged in 2020-10, with the labels that each got.

#292 Auto-generate documentation for Wiki
  build/scripts/Build-Wiki.ps1
Labels: documentation

#293 Add missing .SYNOPSIS to functions
  GitHubAssignees.ps1
  GitHubCore.ps1
  GitHubEvents.ps1
  GitHubIssueComments.ps1
  GitHubLabels.ps1
  GitHubMilestones.ps1
  GitHubProjectCards.ps1
  GitHubProjectColumns.ps1
  GitHubProjects.ps1
Labels: documentation

#294 Fix potential call depth overflow error when retrying a 202 response
  GitHubConfiguration.ps1
  GitHubCore.ps1
  Tests/GitHubRepositories.tests.ps1
Labels: bug

#295 Fixed a copy-paste error
  GitHubContents.ps1
Labels: api-contents, bug

#298 Add reference to Wiki in USAGE.md
  USAGE.md
Labels: documentation
