Repository microsoft/PowerShellForGitHub, pull requests merged in 2020-08, with the labels that each got.

#254 PowerShellForGitHub: Improve and Standardise WhatIf/Confirm Processing
  GitHubAnalytics.ps1
  GitHubAssignees.ps1
  GitHubBranches.ps1
  GitHubConfiguration.ps1
  GitHubContents.ps1
  GitHubCore.ps1
  GitHubEvents.ps1
  GitHubGistComments.ps1
  GitHubGists.ps1
  GitHubIssueComments.ps1
  GitHubIssues.ps1
  GitHubLabels.ps1
  GitHubMilestones.ps1
  GitHubMiscellaneous.ps1
  GitHubOrganizations.ps1
  GitHubProjectCards.ps1
  GitHubProjectColumns.ps1
  GitHubProjects.ps1
  GitHubPullRequests.ps1
  GitHubReactions.ps1
  GitHubReleases.ps1
  GitHubRepositories.ps1
  GitHubRepositoryForks.ps1
  GitHubRepositoryTraffic.ps1
  GitHubTeams.ps1
  GitHubUsers.ps1
  Helpers.ps1
  Telemetry.ps1
Labels: enhancement, waiting for update

#271 Fix GitHubRepositorySecurityFix tests
  Tests/GitHubRepositories.tests.ps1
Labels: api-repositories, tests

#257 GitHubTeams: Add New/Update/Remove Functions
  Formatters/GitHubTeams.Format.ps1xml
  GitHubTeams.ps1
  PowerShellForGitHub.psd1
  Tests/GitHubTeams.tests.ps1
  USAGE.md
Labels: api completeness, api-teams, waiting for update

#274 Removing NoStatus from the module
  GitHubAssignees.ps1
  GitHubBranches.ps1
  GitHubConfiguration.ps1
  GitHubContents.ps1
  GitHubCore.ps1
  GitHubEvents.ps1
  GitHubGistComments.ps1
  GitHubGists.ps1
  GitHubIssueComments.ps1
  GitHubIssues.ps1
  GitHubLabels.ps1
  GitHubMilestones.ps1
  GitHubMiscellaneous.ps1
  GitHubOrganizations.ps1
  GitHubProjectCards.ps1
  GitHubProjectColumns.ps1
  GitHubProjects.ps1
  GitHubPullRequests.ps1
  GitHubReactions.ps1
  GitHubReleases.ps1
  GitHubRepositories.ps1
  GitHubRepositoryForks.ps1
  GitHubRepositoryTraffic.ps1
  GitHubTeams.ps1
  GitHubUsers.ps1
  Helpers.ps1
Labels: technical debt

#277 Update New-GitHubBranch pipeline support
  GitHubBranches.ps1
  Tests/GitHubBranches.tests.ps1
Labels: api-refs, technical debt

#276 Updates all state-changing commands to be silent by default (with -Passthru)
  GitHubAssignees.ps1
  GitHubConfiguration.ps1
  GitHubContents.ps1
  GitHubGistComments.ps1
  GitHubGists.ps1
  GitHubIssueComments.ps1
  GitHubIssues.ps1
  GitHubLabels.ps1
  GitHubMilestones.ps1
  GitHubProjectCards.ps1
  GitHubProjectColumns.ps1
  GitHubProjects.ps1
  GitHubReactions.ps1
  GitHubReleases.ps1
  GitHubRepositories.ps1
  GitHubTeams.ps1
  GitHubUsers.ps1
  Tests/GitHubAssignees.tests.ps1
  Tests/GitHubContents.tests.ps1
  Tests/GitHubEvents.tests.ps1
  Tests/GitHubGistComments.tests.ps1
  Tests/GitHubGists.tests.ps1
  Tests/GitHubIssueComments.tests.ps1
  Tests/GitHubIssues.tests.ps1
  Tests/GitHubLabels.tests.ps1
  Tests/GitHubMilestones.tests.ps1
  Tests/GitHubProjectCards.tests.ps1
  Tests/GitHubProjectColumns.tests.ps1
  Tests/GitHubProjects.tests.ps1
  Tests/GitHubReleases.tests.ps1
  Tests/GitHubRepositories.tests.ps1
  Tests/GitHubTeams.tests.ps1
  USAGE.md
Labels: breaking change, enhancement

#275 Improvements to GitHub Team API's
  Formatters/GitHubTeams.Format.ps1xml
  GitHubTeams.ps1
  PowerShellForGitHub.psd1
  Tests/GitHubTeams.tests.ps1
Labels: api-teams, breaking change, enhancement

#278 Updating module version to 0.15.0
  CHANGELOG.md
  PowerShellForGitHub.psd1
Labels: release

#279 Enhancing CHANGELOG for 0.15.0
  CHANGELOG.md
  GitHubContents.ps1
  GitHubIssueComments.ps1
  GitHubPullRequests.ps1
  GitHubRepositories.ps1
  GitHubUsers.ps1
Labels: bug, documentation
